# public/admin/config.yml

backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: 'Create {{collection}} "{{slug}}"'
    update: 'Update {{collection}} "{{slug}}"'
    delete: 'Delete {{collection}} "{{slug}}"'
    uploadMedia: '[skip ci] Upload "{{path}}"'
    deleteMedia: '[skip ci] Delete "{{path}}"'

# Enable local backend in development
local_backend: true

# Media and public folder
media_folder: "public/uploads"
public_folder: "/uploads"

# Collections define the content structure
collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "coverImage", widget: "image", required: false }
      - { label: "Excerpt", name: "excerpt", widget: "text" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Categories", name: "categories", widget: "list" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Status", name: "status", widget: "select", options: ["draft", "published"] }
      - { label: "Content", name: "content", widget: "markdown" }

  - name: "courses"
    label: "Courses"
    folder: "content/courses"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Language", name: "language", widget: "select", options: ["Norwegian", "English", "Spanish"] }
      - { label: "Level", name: "level", widget: "select", options: ["A1", "A2", "B1", "B2", "C1"] }
      - { label: "Duration", name: "duration", widget: "string" }
      - { label: "Schedule", name: "schedule", widget: "string" }
      - { label: "Price", name: "price", widget: "number" }
      - { label: "Max Students", name: "maxStudents", widget: "number" }
      - { label: "Start Date", name: "startDate", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Course Image", name: "imageUrl", widget: "image" }

  - name: "teachers"
    label: "Teachers"
    folder: "content/teachers"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Role", name: "role", widget: "string" }
      - { label: "Bio", name: "bio", widget: "text" }
      - { label: "Profile Image", name: "image", widget: "image" }
      - { label: "Languages", name: "languages", widget: "list" }